artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/uc?id=183Q4dQHRHc6YuIiYrquREdrAgxQGGqAU
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train.csv", "test.csv", "validation.csv"]
  data_path: artifacts/data_ingestion/data


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data
  train_dataset: artifacts/data_transformation/dataset_train
  val_dataset: artifacts/data_transformation/dataset_validation
  tokenizer_name: t5-base


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/dataset_train
  val_data_path: artifacts/data_transformation/dataset_validation
  model_ckpt: t5-base
  model_pickle: artifacts/model_trainer/model
  tokenizer_pickle: artifacts/model_trainer/tokenizer


model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_ingestion/data/test.csv
  model_path: artifacts/model_trainer/model_t5
  tokenizer_path: artifacts/model_trainer/tokenizer_t5
  model_pkl: artifacts/model_trainer/model
  tokenizer_pkl: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv


prediction:
  model_path: artifacts/model_trainer/model
  tokenizer_path: artifacts/model_trainer/tokenizer